### ISSUE TITLE
Review VnV Plan - Professor 

### ISSUE THREAD

**Issue by NadaElmasry** [NadaElmasry/3D-Image-Reconstruction-Segmentation#10]
Hi Dr.Smith,

Please review my initial [VnV Plan](https://github.com/NadaElmasry/3D-Image-Reconstruction-Segmentation/blob/main/docs/VnVPlan/VnVPlan.pdf) document. 

Thank you!

**Comment by smiths** [comment]
Okay.  In the future, please assign me this issue on the deadline, or explicitly ask for an extension.

**Comment by smiths** [comment]
[Nada_VnVPlan.pdf](https://github.com/NadaElmasry/3D-Image-Reconstruction-Segmentation/files/14566777/Nada_VnVPlan.pdf)
