### ISSUE TITLE
VnV Review from secondary Reviewer

### ISSUE THREAD

**Issue by gordonwky** [NadaElmasry/3D-Image-Reconstruction-Segmentation#11]
I have written some comments on your document
[VnVPlan-2.pdf](https://github.com/NadaElmasry/3D-Image-Reconstruction-Segmentation/files/14389433/VnVPlan-2.pdf)

**Comment by NadaElmasry** [comment]
Hi Gordon! Thank you so much for your review! I'll make sure to address any problems and take any advice of improvement into account in my next version.
