### ISSUE TITLE
Review MG+MIS Plans - Professor

### ISSUE THREAD

**Issue by NadaElmasry** [NadaElmasry/3D-Image-Reconstruction-Segmentation#19]
Hi Dr.Smith,

Please review my initial [MG](https://github.com/NadaElmasry/3D-Image-Reconstruction-Segmentation/blob/main/docs/Design/SoftArchitecture/MG.pdf) and [MIS] (https://github.com/NadaElmasry/3D-Image-Reconstruction-Segmentation/blob/main/docs/Design/SoftDetailedDes/MIS.pdf)plans. 

Thank you!

**Comment by smiths** [comment]
[NadaMG.pdf - PDF Expert.pdf](https://github.com/NadaElmasry/3D-Image-Reconstruction-Segmentation/files/14846240/NadaMG.pdf.-.PDF.Expert.pdf)
[NadaMIS.pdf - PDF Expert.pdf](https://github.com/NadaElmasry/3D-Image-Reconstruction-Segmentation/files/14846241/NadaMIS.pdf.-.PDF.Expert.pdf)
