### ISSUE TITLE
Review MG+MIS Plans - Primary Reviewer

### ISSUE THREAD

**Issue by NadaElmasry** [NadaElmasry/3D-Image-Reconstruction-Segmentation#20]
Hi Yi-Leng,

Please review my initial [MG](https://github.com/NadaElmasry/3D-Image-Reconstruction-Segmentation/blob/main/docs/Design/SoftArchitecture/MG.pdf) and [MIS](https://github.com/NadaElmasry/3D-Image-Reconstruction-Segmentation/blob/main/docs/Design/SoftDetailedDes/MIS.pdf) plans. 

Thank you!

**Comment by kypss94132** [comment]
Hi, Nada,
The feedback for these documents is provided in #22 #23 #24 #25 #26  respectively. Thank you.
