### ISSUE TITLE
Review MG+MIS Plans - Secondary Reviewer

### ISSUE THREAD

**Issue by NadaElmasry** [NadaElmasry/3D-Image-Reconstruction-Segmentation#21]
Hi Morteza!

Please review my initial [MG](https://github.com/NadaElmasry/3D-Image-Reconstruction-Segmentation/blob/main/docs/Design/SoftArchitecture/MG.pdf) and [MIS](https://github.com/NadaElmasry/3D-Image-Reconstruction-Segmentation/blob/main/docs/Design/SoftDetailedDes/MIS.pdf) plans. 

Thank you!

**Comment by mirzaim** [comment]
Hi Nada,

I've had a chance to review your designs, and overall, it's really good.
Here are my reviews:
#27, #28, #29, #30, #31

Thanks,
Morteza
