### ISSUE TITLE
Review Exception Handling in 2D Slice Module (2DSlicer)

### ISSUE THREAD

**Issue by mirzaim** [NadaElmasry/3D-Image-Reconstruction-Segmentation#31]
In the MIS for the 2D Slice Module (2DSlicer), an exception called "SlicingError" is defined for the "get slice data" access program. However, it's stated in the assumptions that the input scan is preprocessed and is in the correct format. Therefore, it seems redundant to include an exception for "input incorrect dimensions" if the input format is already assumed to be correct.

**Comment by NadaElmasry** [comment]
Updated in latest Revision. Thank you for the feedback!
