### ISSUE TITLE
Review SRS Document - Professor

### ISSUE THREAD

**Issue by NadaElmasry** [NadaElmasry/3D-Image-Reconstruction-Segmentation#4]
Hi Dr.Smith,

Please review my initial [SRS](https://github.com/NadaElmasry/3D-Image-Reconstruction-Segmentation/blob/main/docs/SRS/SRS.pdf) document. I will make a separate issue for the primary and secondary reviewers after they accept my invitation.

Thank you!

**Comment by smiths** [comment]
The feedback is attached.  You may wish to create issues from the feedback to organize your work and clearly show the changes between the current version and the final version.  The grade will be posted on Avenue soon.

[NadaElmasry_SRS.pdf](https://github.com/NadaElmasry/3D-Image-Reconstruction-Segmentation/files/14390880/NadaElmasry_SRS.pdf)
