### ISSUE TITLE
Review SRS Document - Primary Reviewer

### ISSUE THREAD

**Issue by NadaElmasry** [NadaElmasry/3D-Image-Reconstruction-Segmentation#5]
Hi Yi-Leng,

Please review my initial [SRS](https://github.com/NadaElmasry/3D-Image-Reconstruction-Segmentation/blob/main/docs/SRS/SRS.pdf) document. 

Thank you!

**Comment by kypss94132** [comment]
Hi, Nada. My apologies for the delayed response.
Your document is well-written and generally easy to understand.

I've already provided some feedback on a couple of points in issues [#7](https://github.com/NadaElmasry/3D-Image-Reconstruction-Segmentation/issues/7) and [#8](https://github.com/NadaElmasry/3D-Image-Reconstruction-Segmentation/issues/8). Take a look whenever you get the chance. Thanks!
