### ISSUE TITLE
SRS Review(writing suggestions)

### ISSUE THREAD

**Issue by kypss94132** [NadaElmasry/3D-Image-Reconstruction-Segmentation#7]
Hi, Nada. Below are some writing suggestions for your SRS document:

- [ ] In Section 1.2, the content was not ordered alphabetically.

- [ ] In Section 2, the paragraph indentation was inconsistent.

- [ ] In Section 2.3, there is a lack of space after the sentence "It would be..."

- [ ] In Section 3.1, some points end with periods, while others do not. Additionally, in the "User Responsibilities" part, the second point is not capitalized. In the "ProgName Responsibilities" part, the project name was not changed.

- [ ] In Section 4.1.1, the first word is not capitalized.

- [ ] In Section 4.1.2, there is a lack of space before the sentence "This approach..."

- [ ] In Section 4.2, the paragraph indentation is inconsistent.

- [ ] In Section 4.2.4, for DD2 and DD3, there is an extra line for the "Description" row.

- [ ] In Sections 5.1 and 5.2, some points end with periods, while others do not.

Possible improvements: It will be better if the size of figure 1 can be bigger. Readers may need to zoom in to clearly see the text on the figure. Also, one of the sentence of the arrow was lack of period.

**Comment by smiths** [comment]
@kypss94132 in the future please separate your points into separate issues.  For related points you can create one issue, but use a checklist, like:

For Section X

- [ ] grammar error 1
- [ ] grammar error 2
- [ ] spelling mistake 1
- [ ] ...

The items can be checked off as they are completed.
